export const authConstants = {
  USER_STATE_CHANGED: 'auth/USER_STATE_CHANGED',
  USER_LOGIN: 'auth/USER_LOGIN',
  USER_LOGOUT: 'auth/USER_LOGOUT',
  USER_SIGNUP: 'auth/USER_SIGNUP',
  USER_RECOVER_USER: 'auth/USER_RECOVER_USER',
  FETCH_USER: 'auth/FETCH_USER',
  UPDATE_USER_INFO: 'auth/UPDATE_USER_INFO',
  CLEAN_USER: 'auth/CLEAN_USER',
  UPLOAD_IMAGE: 'auth/UPLOAD_IMAGE',
  UPDATE_USER_NAME: 'auth/UPDATE_USER_NAME',
  SHOW_LOG_OUT_MODAL: 'auth/SHOW_LOG_OUT_MODAL',
};
