export const tasksConstants = {
  SHOW_CREATE_MODAL: 'tasks/SHOW_CREATE_MODAL',
  CREATE_TASK: 'tasks/CREATE_TASK',
  UPDATE_TASK: 'tasks/UPDATE_TASK',
  CONNECT_TASKS_STATE: 'tasks/CONNECT_TASKS_STATE',
  UPDATE_TASKS_STATE: 'tasks/UPDATE_TASKS_STATE',
  SHOW_UPDATE_MODAL: 'tasks/SHOW_UPDATE_MODAL',
  DELETE_TASK: 'tasks/DELETE_TASK',
  CLEAN_UP: 'tasks/CLEAN_UP',
  SELECT_TASK: 'tasks/SELECT_TASK',
};
