# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane




default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end


FB_ANDROID_APP_ID = "1:981929125796:android:f86e31612f8157d82d4331"



lane :build do
  sh("cd .. && ./scripts/getCredentials.sh")
  gradle(taks:"clean bundleRelease", project_dir: 'android/')
  upload_to_play_store(track:'internal', aab: '/android/app/build/outputs/bundle/release/app-release.aab')
end

lane :build_firebase_android do

  gradle("task: clean assembleRelease", project_dir: 'android/')

  firebase_app_distribution(
    app:FB_ANDROID_APP_ID,
    groups:"testers"
  )
end